WIP: MELQ-85: Add Menu Component
bitia-ru/melq pull request #104
Opened 2020-07-21 19:17 UTC by SergBlack

2020-08-06 19:52 UTC, SvetlanaBatova requested changes
1. Иконки добавить и редактировать сейчас с более толстой линией, чем в дизайне
2. В дизайне у выделенного пункта меню есть отступ слева, сейчас у всех пунктов отступ одинаковый
3. В дизайне есть состояние, когда пункт меню выделен не только при клике, сейчас в example такое состояние не понятно как реализовать

2020-08-06 19:52 UTC, SvetlanaBatova commented on frontend/src/v1/examples/MenuExample.js
> +        src: `${require('../../../img/settings.svg')}#settings`,
Лучше иконки от меню сложить вместе с меню

2020-08-07 11:51 UTC, SergBlack commented on frontend/src/v1/examples/MenuExample.js
> +        src: `${require('../../../img/settings.svg')}#settings`,
Перенес в папку Menu/images

2020-08-07 11:51 UTC, SergBlack commented
>     1. вить и редактировать сейчас с более толстой линией, чем в дизай

2020-08-07 13:26 UTC, SergBlack commented
>     1. Иконки добавить и редактировать сейчас с более толстой линией, чем в дизайне
Прописал для иконок в path атрибут stroke-width="0"
>     2. В дизайне у выделенного пункта меню есть отступ слева, сейчас у всех пунктов отступ одинаковый
Теперь отсуп задается когда компонент Link переходит при клике в состояние <Link selected={true} />
>     3. В дизайне есть состояние, когда пункт меню выделен не только при клике, сейчас в example такое состояние не понятно как реализовать
Сделал возможным активировать в момент времени только один пункт меню

2020-08-07 13:27 UTC, SergBlack commented
>     1. Иконки добавить и редактировать сейчас с более толстой линией, чем в дизайне
> 
>     2. В дизайне у выделенного пункта меню есть отступ слева, сейчас у всех пунктов отступ одинаковый
> 
>     3. В дизайне есть состояние, когда пункт меню выделен не только при клике, сейчас в example такое состояние не понятно как реализовать

1. Прописал для иконок в path атрибут stroke-width="0"
2. Теперь отсуп задается когда компонент Link переходит при клике в состояние <Link selected={true} />
3. Сделал возможным активировать в момент времени только один пункт меню

2020-08-07 21:43 UTC, SvetlanaBatova commented on frontend/src/v1/examples/MenuExample.js
> +        src: `${require('../../../img/settings.svg')}#settings`,
Да, но судя по роуту используется не оно или я куда-то не туда смотрю?

2020-08-08 08:02 UTC, SvetlanaBatova approved these changes

2020-08-23 11:41 UTC, levenkov commented
![image](https://user-images.githubusercontent.com/35109446/90977498-91876200-e54e-11ea-85f2-e95124ddeca7.png)
А разве не должны быть разные действия при нажатии на сам пункт меню и иконку? Я спросил в чате у Жени.

2020-08-23 11:42 UTC, levenkov commented
Изменение курсора должно подсказывать юзеру, что можно кликать. А тут получается, что курсор меняется только при наведении на текст пункта, а не на весь пункт.

2020-08-23 18:32 UTC, SergBlack commented
> Изменение курсора должно подсказывать юзеру, что можно кликать. А тут получается, что курсор меняется только при наведении на текст пункта, а не на весь пункт.



> ![image](https://user-images.githubusercontent.com/35109446/90977498-91876200-e54e-11ea-85f2-e95124ddeca7.png)
> А разве не должны быть разные действия при нажатии на сам пункт меню и иконку? Я спросил в чате у Жени.

Да, так и предусмотрено, но для examle у Link и Icon общая функция, завязанная на localstate

2020-08-23 18:47 UTC, SergBlack commented
> Изменение курсора должно подсказывать юзеру, что можно кликать. А тут получается, что курсор меняется только при наведении на текст пункта, а не на весь пункт.



> Изменение курсора должно подсказывать юзеру, что можно кликать. А тут получается, что курсор меняется только при наведении на текст пункта, а не на весь пункт.

Пока это сделано умышленно. Были вопросы к дизайну - как вообще должно быть реализовано это меню, но из-за отпусков отложился вопрос. Сделаю так, как будет решено после обсуждения в чате

2020-08-30 11:16 UTC, levenkov requested changes

2020-08-30 11:16 UTC, levenkov commented on frontend/src/v1/components/Menu/Menu.jsx
> +    menuItems={menuItems}
А зачем передавать через пропсы? Удобней же через body.

Там встанет вопрос, как проверить, что все элементы body являются MenuItem. Ответ — никак. Не надо это проверять. Ничего не сломается от передачи не MenuItems и ничего страшного от того, что не сломается, не будет.

2020-08-30 11:16 UTC, levenkov commented on frontend/src/v1/components/Menu/MenuLayout.jsx
> +      menuItems.map(menuItem => (
Coding style: Каждый аргумент должен занимать выделенные строки.

2020-08-30 11:16 UTC, levenkov commented on frontend/src/v1/components/MenuItem/MenuItem.jsx
> +const MenuItem = ({ id, menuItem }) => (
Элемент меню, передаваемый в элемент меню? :) Это как так? :)

Видимо это пропс, содержащий опции элемента меню. Но зачем их в один объект упаковывать? Так можно вообще всегда все пропсы упаковывать в объекты и у каждого компонента всегда будет только один пропс.

2020-08-30 11:16 UTC, levenkov commented on frontend/src/v1/components/MenuItem/MenuItemLayout.jsx
> +  const { link, icon, disabled } = menuItem;
Интересно, нельзя ли было бы написать так:

```
const MenuItemLayout = ({ id, { link, icon, disabled } }) => {
```

2020-11-27 08:52 UTC, closed without merging