MELQ-108: Для компонента Counter предусмотреть возможность задавать размер
bitia-ru/melq pull request #114
Opened 2020-07-24 12:05 UTC by SergBlack

2020-07-27 12:42 UTC, SvetlanaBatova requested changes

2020-07-27 12:42 UTC, SvetlanaBatova commented on frontend/src/v1/components/Counter/CounterLayout.jsx
> +  };
Зачем две одинаковых функции и зачем switch, если варианта пока только два?

2020-07-27 12:42 UTC, SvetlanaBatova commented on frontend/src/v1/components/Counter/CounterLayout.jsx
> +            <use xlinkHref={src} width={getWidth()} height={getHeight()} />
Здесь точно нужно задавать width и height? того, что они заданы для svg не хватает?

2020-07-27 12:42 UTC, SvetlanaBatova commented on frontend/src/v1/components/Counter/CounterLayout.jsx
> +                size === 'small' && styles.counterValueSmallMargin,
size === 'small' ? styles.counterValueSmallMargin : styles.counterValueDefaultMargin не тоже самое одной строкой?

2020-07-27 12:42 UTC, SvetlanaBatova commented on frontend/src/v1/components/Counter/CounterLayout.jsx
> +      return width * 0.65;
Почему 0.65? Вроде решили, что должно уменьшаться на 30% ?

2020-07-28 13:01 UTC, SergBlack commented on frontend/src/v1/components/Counter/CounterLayout.jsx
> +            <use xlinkHref={src} width={getWidth()} height={getHeight()} />
Убрано

2020-07-28 13:08 UTC, SergBlack commented on frontend/src/v1/components/Counter/CounterLayout.jsx
> +  };
Функции объединил в одну. Зарефакторил

2020-07-28 13:10 UTC, SergBlack commented on frontend/src/v1/components/Counter/CounterLayout.jsx
> +                size === 'small' && styles.counterValueSmallMargin,
Поправил

2020-07-28 13:15 UTC, SergBlack commented on frontend/src/v1/components/Counter/CounterLayout.jsx
> +      return width * 0.65;
Поправил

2020-07-28 14:19 UTC, levenkov approved these changes

2020-07-28 14:40 UTC, SvetlanaBatova approved these changes

2020-07-28 14:51 UTC, merged