MELQ-5: Add image to post without saving
bitia-ru/melq pull request #15
Opened 2020-05-29 15:56 UTC by SvetlanaBatova

2020-06-07 07:56 UTC, levenkov requested changes
Все работает именно так, как надо вроде, но есть одна ошибочка: при просмотре поста линк на изображение неправильный. У меня все выглядит так, будто при просмотре изображения линк вообще не обработан (`<img src="xxx.png" />`). Возможно это я сломал в процессе ребейза, проверь пожалуйста.

2020-06-07 09:36 UTC, SvetlanaBatova commented
Попробовала, у меня проблема не воспроизводится, изображение отображается в виде <img src="/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBDZz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--18d13d32f7083544bce7be71bde508a8383bd032/download1.png" alt="img">

2020-06-07 09:40 UTC, levenkov commented
Проверь, что у тебя нет ошибки при таком же способе воспроизведения, как у меня:

1. Запускаю через `docker-compose up -d` (т.е. все через докер)
2. Пост создаю не логинясь
3. Просматриваю пост тоже не логинясь
4. Имя фотографии я менял после загрузки

2020-06-07 11:11 UTC, SvetlanaBatova commented
Проблема не в том, что неправильно отображается, а в том, что не сохраняется имя файла при его редактировании. Вроде поправила

2020-06-08 10:24 UTC, levenkov commented
Теперь работает. Изучаю теперь код.

2020-06-08 11:38 UTC, levenkov requested changes

2020-06-08 11:38 UTC, levenkov commented on frontend/src/v1/utils/prepareImageUrls.js
> +      const re = new RegExp(`!\\[(.*)]\\(${filename}\\)`)
Под эту регулярку попадает, например, такое: `![foo](blabla.jpg) ... ![bar](xxx.jpg)`. Если регулярка работает как жадная - она съест все это выражение. Надо проверить, что этого не происходит или даже просто явно запретить символы `]` внутри квадратных скобок и `)` внутри круглых.

2020-06-19 01:18 UTC, levenkov requested changes

2020-06-19 01:18 UTC, levenkov commented on backend/app/controllers/api/v1/posts_controller.rb
> +            next unless attachment[:id]
По смыслу обе эти строчки означают "пропустить, если attachment не содержит один из данных ключей". Можно написать код, который будет гораздо ближе к данному утверждению.

2020-06-19 01:21 UTC, levenkov requested changes
Проверь подсветку замечаний в IDE

2020-06-19 01:21 UTC, levenkov commented on frontend/src/v1/screens/PostEdit.jsx
> +    let { slug } = this.props.match.params;
Где меняется `slug`?

2020-06-19 09:12 UTC, SvetlanaBatova commented on frontend/src/v1/utils/prepareImageUrls.js
> +      const re = new RegExp(`!\\[(.*)]\\(${filename}\\)`)
Проверила, этого не происходит, добавила ограничение на использование квадратных скобок внутри квадратных, для круглых скобок по идее ограничение итак есть, т.к здесь внутри скобок может быть только filename, а он ограничен по возможным символам и круглых скобок в нем быть не может

2020-06-19 09:13 UTC, SvetlanaBatova commented on frontend/src/v1/screens/PostEdit.jsx
> +    let { slug } = this.props.match.params;
нигде, поменяла let на const

2020-06-19 09:44 UTC, SvetlanaBatova commented on backend/app/controllers/api/v1/posts_controller.rb
> +            next unless attachment[:id]
Заменила на одну строчку, но возможно имелось ввиду что-то другое?

2020-06-19 09:46 UTC, SvetlanaBatova commented
> Проверь подсветку замечаний в IDE

Завела отдельный тикет MELQ-39, в котором отключила react/destructuring-assignment, ребейзнула на него и по тем файлам, которые редактируются в рамках данного тикета по максимуму поправила то, на что ругается eslint

2020-06-19 12:45 UTC, levenkov requested changes

2020-06-19 12:45 UTC, levenkov commented on backend/app/controllers/api/v1/posts_controller.rb
> +            next unless %i[id filename].all?{|k| attachment.include?(k)}
Вроде тут пришли к выводу, что лучше не так записывать.

2020-06-19 13:15 UTC, SvetlanaBatova commented on backend/app/controllers/api/v1/posts_controller.rb
> +            next unless attachment[:id]
Заменила на (%i[id filename] - attachment.keys).empty?

2020-06-19 13:15 UTC, SvetlanaBatova commented on backend/app/controllers/api/v1/posts_controller.rb
> +            next unless %i[id filename].all?{|k| attachment.include?(k)}
Заменила на (%i[id filename] - attachment.keys).empty?

2020-06-19 19:40 UTC, levenkov approved these changes

2020-06-19 19:42 UTC, merged