WIP: MELQ-1: Lay the foundation
bitia-ru/melq pull request #2
Opened 2020-05-25 18:03 UTC by SvetlanaBatova

2020-05-25 19:46 UTC, levenkov commented
Переименуй `gw_auth` в `gw`.

2020-05-28 12:14 UTC, levenkov requested changes

2020-05-28 12:14 UTC, levenkov commented on .gitignore
> +/gcs-credentials.json
Этого файла здесь вообще быть не должно: мы гугло-стором не пользуемся здесь.

2020-05-28 12:14 UTC, levenkov commented on auth/Gemfile
> +gem 'sidekiq'
Аусу разве нужен sidekiq?

2020-05-28 12:14 UTC, levenkov commented on auth/app/validators/user_validator.rb
> +    unless user.email.present? || user.login.present? || user.phone.present?
Это зачем? У нас логина нет, телефона тоже пока.

2020-05-28 12:32 UTC, levenkov requested changes

2020-05-28 12:32 UTC, levenkov commented on gw/app/static/foo.css
> +.test {
Давай уберем из gw неиспользуемые вещи.

2020-05-28 12:32 UTC, levenkov commented on frontend/webpack.config.js
> +      CLIENT_ID: '',
Это нам тут вроде не нужно?

2020-05-28 12:32 UTC, levenkov commented on frontend/src/v1/store.js
> +    try {
Это зачем?

2020-05-28 12:32 UTC, levenkov commented on docker-compose.yml
> +        clientId: ${CLIENT_ID:-6454126}
Удаляем?

2020-05-28 12:32 UTC, levenkov commented on docker-compose.yml
> +      - ${PWD}/gcs-credentials.json:/etc/gcs-credentials.json
Убираем

2020-05-28 12:32 UTC, levenkov commented on docker-compose.yml
> +      STORAGE_GCS_PROJECT: ${STORAGE_GCS_PROJECT:-bitia-191612}
Эти две строчки тоже не нужны

2020-05-28 12:32 UTC, levenkov commented on docker-compose.yml
> +      ELASTICSEARCH_URL: ${ELASTICSEARCH:-http://localhost:9200}
И это не нужно

2020-05-28 12:32 UTC, levenkov commented on docker-compose.yml
> +      CLIENT_ID: ${CLIENT_ID:-6454126}
Проверь все переменные окружения на вопрос необхоидмости

2020-05-28 12:32 UTC, levenkov commented on backend/db/seeds.rb
> +  password_digest: '$2a$10$LkpmdSE/GfLjPWHfcqMFo.vG5.CgJluYsrV5sNQCgPOT3JuShNp/.',
Добавь здесь комментарий, что это за пароль

2020-05-28 12:32 UTC, levenkov commented on backend/db/migrate/20181109115711_initial_migration.rb
> +        'auth_only', 'everyone', 'noone'
Вместо noone чаще всего используют nobody.
auth_only - давай не сокращать, давай `authorized_only`.

2020-05-28 12:32 UTC, levenkov commented on backend/db/seeds.rb
> +  password_digest: '$2a$10$LkpmdSE/GfLjPWHfcqMFo.vG5.CgJluYsrV5sNQCgPOT3JuShNp/.',
И запись Setting давай сразу создадим

2020-05-28 13:59 UTC, SvetlanaBatova commented on .gitignore
> +/gcs-credentials.json
убрала

2020-05-28 13:59 UTC, SvetlanaBatova commented on auth/Gemfile
> +gem 'sidekiq'
не нужен, убрала здесь и все, что с ним связано

2020-05-28 13:59 UTC, levenkov approved these changes

2020-05-28 14:00 UTC, SvetlanaBatova commented on auth/app/validators/user_validator.rb
> +    unless user.email.present? || user.login.present? || user.phone.present?
этот валидатор не нужен, он не используется, удалила

2020-05-28 14:00 UTC, SvetlanaBatova commented on gw/app/static/foo.css
> +.test {
убрала

2020-05-28 14:00 UTC, SvetlanaBatova commented on frontend/webpack.config.js
> +      CLIENT_ID: '',
не нужно, убрала

2020-05-28 14:01 UTC, SvetlanaBatova commented on frontend/src/v1/store.js
> +    try {
Сейчас не нужно, убрала

2020-05-28 14:01 UTC, SvetlanaBatova commented on docker-compose.yml
> +        clientId: ${CLIENT_ID:-6454126}
удалила

2020-05-28 14:01 UTC, SvetlanaBatova commented on docker-compose.yml
> +      - ${PWD}/gcs-credentials.json:/etc/gcs-credentials.json
убрала

2020-05-28 14:01 UTC, SvetlanaBatova commented on docker-compose.yml
> +      STORAGE_GCS_PROJECT: ${STORAGE_GCS_PROJECT:-bitia-191612}
удалила

2020-05-28 14:02 UTC, SvetlanaBatova commented on docker-compose.yml
> +      ELASTICSEARCH_URL: ${ELASTICSEARCH:-http://localhost:9200}
удалила

2020-05-28 14:02 UTC, SvetlanaBatova commented on docker-compose.yml
> +      CLIENT_ID: ${CLIENT_ID:-6454126}
Вроде все лишнее удалила

2020-05-28 14:03 UTC, SvetlanaBatova commented on backend/db/seeds.rb
> +  password_digest: '$2a$10$LkpmdSE/GfLjPWHfcqMFo.vG5.CgJluYsrV5sNQCgPOT3JuShNp/.',
Сделала, чтобы пароль задавался явно, добавила Setting и два поста для about и policy

2020-05-28 14:03 UTC, SvetlanaBatova commented on backend/db/migrate/20181109115711_initial_migration.rb
> +        'auth_only', 'everyone', 'noone'
Поменяла, тогда это нужно поправить в MELQ-3

2020-05-29 07:00 UTC, merged