WIP: MELQ-19: Introduce ws
bitia-ru/melq pull request #20
Opened 2020-06-03 15:38 UTC by SvetlanaBatova

2020-06-19 01:35 UTC, levenkov requested changes
Проверь подсветку замечаний в IDE.

2020-06-19 01:35 UTC, levenkov commented on auth/app/controllers/concerns/purable.rb
> +    @body[:entities] = if params[:action] == 'index' || purable_resource_params.is_a?(Array)
Отступы должны быть тут 2 символа, а не выровнены по `if`.

2020-06-19 01:35 UTC, levenkov commented on auth/app/views/application/index.json.jbuilder
> +      json.set!(resources_name) do
Вот этот фрагмент много где повторяется. Давай его вынесем в отдельный файл.

2020-06-19 01:35 UTC, levenkov commented on backend/app/models/comment.rb
> +        'all',
Странные отступы.

2020-06-19 01:35 UTC, levenkov commented on frontend/src/v1/index.js
> +      console.log(store);
Кажется, это мусор

2020-06-19 01:35 UTC, levenkov commented on frontend/src/v1/redux/comments/actions.js
> +    dispatch({
В одну строчку влезает. Подобных строчек у тебя очень много. Не плоди строчки без лишней необходимости, тут ведь всего один ключ.

2020-06-19 01:35 UTC, levenkov commented on frontend/src/v1/redux/tags/reducer.js
> +        R.fromPairs(R.map(tag => [tag.id, tag], action.tags)),
Лучше вложенные вызовы на отдельных строчках писать (если у них аргументы не тривиальные).

```
foo(
  bar(...)
)
```

2020-06-19 21:23 UTC, SvetlanaBatova commented on auth/app/controllers/concerns/purable.rb
> +    @body[:entities] = if params[:action] == 'index' || purable_resource_params.is_a?(Array)
Поправила

2020-06-19 21:32 UTC, SvetlanaBatova commented on auth/app/views/application/index.json.jbuilder
> +      json.set!(resources_name) do
Вынесла в отдельные файлы повторяющиеся куски

2020-06-19 21:32 UTC, SvetlanaBatova commented on backend/app/models/comment.rb
> +        'all',
Поправила

2020-06-19 21:33 UTC, SvetlanaBatova commented on frontend/src/v1/index.js
> +      console.log(store);
Удалила

2020-06-19 21:33 UTC, SvetlanaBatova commented on frontend/src/v1/redux/comments/actions.js
> +    dispatch({
Поправила, где нашла

2020-06-19 21:33 UTC, SvetlanaBatova commented on frontend/src/v1/redux/tags/reducer.js
> +        R.fromPairs(R.map(tag => [tag.id, tag], action.tags)),
Поправила

2020-06-28 22:57 UTC, levenkov requested changes

2020-06-28 22:57 UTC, levenkov commented on backend/app/views/api/v1/comments/_comment.json.jbuilder
> +if defined?(destroy) && destroy
Нарушение области ответственности: _comment.json определяет, как должна быть отрендерена сущность Comment. Точка. Про то, как мы передаём признак удаления сущности через контроллеры или WS _comment.json ничего знать не должен.

2020-06-28 22:57 UTC, levenkov commented on frontend/src/v1/redux/comments/actions.js
> +            type: acts.LOAD_COMMENTS_FAILED,
`LOAD_...`?

2020-06-28 22:57 UTC, levenkov commented on frontend/src/v1/redux/comments/constants/defaultStoreFormat.js
> +const DEFAULT_STORE_FORMAT = {
Слово "FORMAT" тут не подходит. Дефолтный формат? Т.е. есть какой-то не-дефолтный? Нет, формат один.

Это скорее initial value.

2020-06-29 11:18 UTC, SvetlanaBatova commented on frontend/src/v1/redux/comments/actions.js
> +            type: acts.LOAD_COMMENTS_FAILED,
Поправим отдельным тикетом по всему проекту

2020-06-29 11:27 UTC, SvetlanaBatova commented on frontend/src/v1/redux/comments/constants/defaultStoreFormat.js
> +const DEFAULT_STORE_FORMAT = {
Переименовала

2020-06-29 11:29 UTC, SvetlanaBatova commented on backend/app/views/api/v1/comments/_comment.json.jbuilder
> +if defined?(destroy) && destroy
Убрала отсюда destroy, сделала так, чтобы в случает удаления шаблон не использовался, а генерировался json только с ключами id и _destroy

2020-06-29 17:38 UTC, levenkov requested changes

2020-06-29 17:38 UTC, levenkov commented on auth/app/controllers/concerns/purable.rb
> +    @body = {}
Я предлагаю записать это так:

```
@body = {
  payload: @payload,
  metadata: @metadata,
  entities: (
    params[:index] || purable_resource_params.is_a?(Array) ? resources : resource
  )
}.compact
```

2020-06-29 21:12 UTC, levenkov requested changes

2020-06-29 21:12 UTC, levenkov commented on auth/app/controllers/concerns/purable.rb
> +    @body = {}
`&& @payload` плохо, т.к. пустые поля разрешает. `&& @payload.present?` — так лучше.

2020-06-29 21:16 UTC, levenkov requested changes

2020-06-29 21:16 UTC, levenkov commented on frontend/src/v1/redux/comments/reducer.js
> +import INITIAL_VALUE from './constants/defaultStoreFormat';
Ну а имя-то файла почему осталось тем же? И мы давно обсуждаем, что надо отказаться от сваливания всех констант в одну кучу. Это не даёт реально ничего, кроме сваленных в кучу констант. Они не работают как конфиги, т.к. среди 100 констант только в лучшем случае десяток является по смыслу конфигурационными.

Поэтому лучше, я думаю, вообще вытащить из отдельного файла `INITIAL_VALUE` и вставить эту константу в файл редьюсера.

2020-06-29 22:29 UTC, levenkov requested changes

2020-06-29 22:29 UTC, levenkov commented on backend/app/views/application/destroy.json.jbuilder
> +            locals: { destroy => true }
Тут destroy — это метод контроллера. Это точно то, что ты предполагала?

2020-06-29 22:29 UTC, levenkov commented on backend/app/views/application/destroy.json.jbuilder
> +          json.partial! "api/v1/#{resources_name}/#{resource_name}", locals: { resource_name => resource }
Длинная строка

2020-06-29 22:29 UTC, levenkov commented on auth/app/views/application/destroy.json.jbuilder
> +          json.partial! "api/v1/#{resources_name}/#{resource_name}", locals: {resource_name => resource}
Длинная строка

2020-06-30 10:43 UTC, SvetlanaBatova commented on auth/app/controllers/concerns/purable.rb
> +    @body = {}
Поправила

2020-06-30 10:44 UTC, SvetlanaBatova commented on frontend/src/v1/redux/comments/reducer.js
> +import INITIAL_VALUE from './constants/defaultStoreFormat';
перенесла в редьюсер

2020-06-30 10:46 UTC, SvetlanaBatova commented on backend/app/views/application/destroy.json.jbuilder
> +            locals: { destroy => true }
Переделала шаблон для destroy так, чтобы не использовались шаблоны, а возвращался json вида {id: ..., _destroy: true} или {slug: ..., _destroy: true} и аналогично для массива

2020-06-30 10:46 UTC, SvetlanaBatova commented on backend/app/views/application/destroy.json.jbuilder
> +          json.partial! "api/v1/#{resources_name}/#{resource_name}", locals: { resource_name => resource }
Поправила

2020-06-30 10:46 UTC, SvetlanaBatova commented on auth/app/views/application/destroy.json.jbuilder
> +          json.partial! "api/v1/#{resources_name}/#{resource_name}", locals: {resource_name => resource}
Поправила

2020-07-05 17:52 UTC, levenkov requested changes
Бекенду ревью сделаю, когда доделаешь (делай сама всё же).

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/index.js
> +      processEntities(store.dispatch, data?.body);
Почему бы не назвать не body, а entities? body в контексте WS ни о чем не говорит.

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/utils/processEntities.js
> +const entityProcessors = {
Эта сущность принадлежит данному конкретному проекту, а всё остальное — концепции, которая может быть использована в разных проектах.

Давай их разделим на два файла.

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/utils/processEntities.js
> +const processEntities = (dispatch, entities) => {
Тут есть искусственно введённое ограничение. Кто нам мешает в entities запихнуть сразу несколько разных сущностей? Например, юзера и его сессию.

Предлагаю поддержать такой случай. Заодно сразу пропадёт это странное ощущение использования словаря с всегда одним ключём (что бросается в глаза по константе 0).

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/utils/getComments.js
> +  const postComments = R.values(R.filter(
Так писать нельзя. Если вызов метода не помещается на одну строку, то каждый аргумент должен занимать выделенные строки (за исключением редких случаев группировки однотипных коротких аргументов типа `x, y,`).

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/utils/getComments.js
> +  const postCommentTree = R.filter(comment => (comment.comment_id === null), postComments);
Это вроде не дерево комментариев как раз. Дерево — это то, что возвращается методом getComments. Если так, то `getComments` → `getCommentsTreeOfPost` и `postCommentsTree` → `rootComments`.

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/utils/getComments.js
> +    comment => ({ ...comment, comments: getResponseComments(comment, postComments) }),
Я бы назвал `getCommentReplies`. Response тут уж очень хочется проассоциировать с HTTP response.

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/utils/getComments.js
> +const getResponseComments = (comment, comments) => (
Возможно не в рамках данного тикета, но я бы предложил написать универсальный алгоритм построения деревьев из массивов. Он на самом деле много где может пригодиться и, что самое важное, вся суть метода getComments именно в этом и состоит. А суть лучше отделять от деталей реализации.

Как ты на это смотришь?

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/utils/entity_processors/post_processor.js
> +  if (post._destroy) { // eslint-disable-line no-underscore-dangle
Тебе не кажется, что это (no-underscore-dangle) правило бесполезно и его надо просто отключить?

Мои соображения:

1. Случайно дать переменной имя, начинающееся с подчеркивания, нельзя никак.
2. В описании правила написано, против чего оно направлено — против архаизма, который мы с тобой вообще не застали. Мы никогда не привыкали писать с подчеркиванием. Единственный случай, когда мы так пишем — это когда имя аргумента надо зачем-то написать, но этот аргумент не будет использован. Ну или совсем уж экзотика, как тут.

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/redux/user_session/reducer.js
> +        0: { user_id: null },
Давай лучше сделаем нормальный ключ типа `self`, а не 0. Когда ниже видишь `[0]`, непонятно, почему берётся просто первый элемент.

2020-07-05 17:52 UTC, levenkov commented on frontend/src/v1/redux/comments/actions.js
> +export const updateComment = (postSlug, id, params, afterSuccess, afterAll) => (
params — это термин HTTP-запроса. Тут вернее было бы `attributes`. Поправь в остальных подобных случаях (если они есть).

2020-07-05 20:01 UTC, SvetlanaBatova commented on frontend/src/v1/index.js
> +      processEntities(store.dispatch, data?.body);
Здесь не должно быть body, ревью сделано на середине переделки формата ответа от бекенда

2020-07-05 20:01 UTC, SvetlanaBatova commented on frontend/src/v1/utils/processEntities.js
> +const entityProcessors = {
Разделила на два файла

2020-07-05 20:02 UTC, SvetlanaBatova commented on frontend/src/v1/utils/processEntities.js
> +const processEntities = (dispatch, entities) => {
Сделала так, чтобы обрабатывались все ключи, которые переданы в entities, убрала обращение к первому элементу

2020-07-05 20:03 UTC, SvetlanaBatova commented on frontend/src/v1/utils/getComments.js
> +  const postComments = R.values(R.filter(
Поправила

2020-07-05 20:03 UTC, SvetlanaBatova commented on frontend/src/v1/utils/getComments.js
> +  const postCommentTree = R.filter(comment => (comment.comment_id === null), postComments);
Переименовала

2020-07-05 20:03 UTC, SvetlanaBatova commented on frontend/src/v1/utils/getComments.js
> +    comment => ({ ...comment, comments: getResponseComments(comment, postComments) }),
Переименовала

2020-07-05 20:04 UTC, SvetlanaBatova commented on frontend/src/v1/utils/getComments.js
> +const getResponseComments = (comment, comments) => (
Попробовала сделать в рамках данного тикета

2020-07-05 20:09 UTC, SvetlanaBatova commented on frontend/src/v1/utils/entity_processors/post_processor.js
> +  if (post._destroy) { // eslint-disable-line no-underscore-dangle
Да, мне кажется, что от этого правила можно отказаться, не уверена, что имеет смысл делать это в рамках этого тикета. У нас есть тикет на задание максимальной длины строки для eslint, можно его расширить и добавить туда отключение этого правила. Еще хотелось бы понять как настроить eslint для использование label, сейчас при привычном использовании возникает ошибка jsx-a11y/label-has-associated-control, возможно имеет смысл туда же включить настройку этого правила

2020-07-05 20:09 UTC, SvetlanaBatova commented on frontend/src/v1/redux/user_session/reducer.js
> +        0: { user_id: null },
Поменяла на self

2020-07-05 20:11 UTC, SvetlanaBatova commented on frontend/src/v1/redux/comments/actions.js
> +export const updateComment = (postSlug, id, params, afterSuccess, afterAll) => (
Это то, что передается в Api под видом params, т.е. в Api это тоже называется params и по сути это и есть не параметры, которые в backend приходят как params, не вижу смысла их переименовывать

2020-07-05 20:23 UTC, levenkov commented on frontend/src/v1/utils/entity_processors/post_processor.js
> +  if (post._destroy) { // eslint-disable-line no-underscore-dangle
Согласен, давай так

2020-07-05 20:24 UTC, levenkov commented on frontend/src/v1/redux/comments/actions.js
> +export const updateComment = (postSlug, id, params, afterSuccess, afterAll) => (
Тут точно нет лишней частицы "не"?

2020-07-05 20:50 UTC, SvetlanaBatova commented on frontend/src/v1/redux/comments/actions.js
> +export const updateComment = (postSlug, id, params, afterSuccess, afterAll) => (
Переименовала

2020-07-06 06:24 UTC, levenkov requested changes

2020-07-06 06:24 UTC, levenkov commented on frontend/src/v1/utils/getCommentsTreeOfPost.js
> +    arr => (R.filter(comment => (comment.comment_id === null), arr)),
Тут и строчкой ниже лишние скобки

2020-07-06 06:24 UTC, levenkov commented on frontend/src/v1/utils/getCommentsTreeOfPost.js
> +    (obj, arr) => (R.filter(c => (c.comment_id === obj.id), arr)),
Это плохо тем, что ты сильно ограничиваешь выбор алгоритма построения дерева. Однопроходный алгоритм (который сложнее реализуется, но заметно эффективней) ты с таким интерфейсом не сделаешь. А интерфейс надо делать таким, чтобы он минимально ограничивал выбор реализации (но при этом оставался быть удобным).

Я бы такой интерфейс предложил:

```
buildTreeFromArray(
  {
    primaryKey: 'id', // Это можно сделать дефолтным значением, но предусмотреть возможность задавать иное
    childrenKeys: 'comments',
    parentKey: 'comment_id',
    // А корневыми можно считать просто, если по родительскому ключу лежит нечто falsy
  },
  postComments,
)
```

2020-07-06 06:24 UTC, levenkov commented on frontend/src/v1/utils/getCommentsTreeOfPost.js
> +    (obj, arr) => (R.filter(c => (c.comment_id === obj.id), arr)),
Даже более того, я бы сделал возможность просто написать `buildTreeFromArray('comments', postComments)`, а словарь в моем комменте выше дать возможность подавать третим аргументом для сложных случаев

2020-07-07 10:19 UTC, SvetlanaBatova commented on frontend/src/v1/utils/getCommentsTreeOfPost.js
> +    (obj, arr) => (R.filter(c => (c.comment_id === obj.id), arr)),
Завела на это отдельный тикет #73

2020-07-07 10:20 UTC, SvetlanaBatova commented on frontend/src/v1/utils/getCommentsTreeOfPost.js
> +    arr => (R.filter(comment => (comment.comment_id === null), arr)),
Убрала лишние скобки

2020-07-07 21:25 UTC, levenkov approved these changes

2020-07-07 21:33 UTC, merged