WIP: MELQ-30: Move posts from db to storage/posts
bitia-ru/melq pull request #31
Opened 2020-06-08 16:40 UTC by SvetlanaBatova

2020-06-09 12:20 UTC, SvetlanaBatova commented
Сейчас текущее состояние по своей функциональности должно соответствовать тому, что было до начала работы с тикетом, но посты и их картинки теперь хранятся в ./storage/posts, а не в базе, все ссылки, которые были в базе на посты заменены на slug. Осталось несколько проблем, которые не должны мешать работе, но реализованы не совсем так, как хотелось бы:
1. При загрузке изображений по идее должно быть можно взять tempfile, в котором лежит загружаемое изображение и скопировать его в нужную папку через cp или FileUtils.cp, но почему-то так сделать не получается, файл появляется, но он битый. Сейчас сделано так, что файл читается, а потом записывается в нужный файл. Возможно проблема в том, что tempfile успевает удалиться до того, как скопироваться
2. Сделать так /posts/:slug/images/:filename -> ./storage/posts/:slug/:filename не получается, так как при этом в params[:filename] оказывается файл без разширения. Сделала пока так /posts/:slug/images?filename=:filename -> ./storage/posts/:slug/:filename, так разширение в params[:filename] не обрубается. И плюс здесь приходится добавлять api/v1, чтобы запрос шел на бекенд или тогда надо это прописывать в gw отдельно
3. Фронт сейчас передает tag_ids, обычный вариант работы с accept_nested без них не работает, в текущей реализации он не используется, поэтому на него написан просто пустой метод. Возможно логичнее этот метод убрать, а из фронта этот параметр не передавать или на стороне бекенда  просто его игнорировать

2020-06-10 08:57 UTC, levenkov requested changes

2020-06-10 08:57 UTC, levenkov commented on backend/app/controllers/api/v1/posts_controller.rb
> +        send_file "#{Rails.root}/storage/posts/#{params[:slug]}/#{params[:filename]}", disposition: 'inline'
Эта строчка не гарантирует, что то, что будет отправлено, обязательно является изображением. Надо подумать, как красиво сделать так, чтобы гарантировалось. Явная проверка тоже выглядит не очень хорошим решением.

2020-06-10 08:57 UTC, levenkov commented
Исправь пункт 2, вот [тут](https://zargony.com/2009/05/05/routing-parameters-with-a-dot) написано как можно исправить.

2020-06-10 12:10 UTC, SvetlanaBatova commented on backend/app/controllers/api/v1/posts_controller.rb
> +        send_file "#{Rails.root}/storage/posts/#{params[:slug]}/#{params[:filename]}", disposition: 'inline'
Мы говорили о том, что хотелось бы, чтобы этого роута вообще не было, возможно у рельсов есть какой-то упрощенный вариант для роута, который должен отдавать картинки. На это есть отдельный тикет, если есть какой-то более простой способ отдавать картинки, то проверка здесь будет не нужна.

2020-06-10 13:21 UTC, SvetlanaBatova commented
> Исправь пункт 2, вот [тут](https://zargony.com/2009/05/05/routing-parameters-with-a-dot) написано как можно исправить.

Исправила

2020-07-28 01:12 UTC, levenkov requested changes

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +                :content,
Лучше так:

```
attr_accessor(
  :title,
  ...
)
```

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    @published = post[:published] || false
Лучше в таких случаях использовать `fetch()`

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    @created_at = post[:created_at].nil? ? nil : post[:created_at].to_datetime
Через `&.` лучше

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +  def self.postsDir
В ruby только `snake_case`

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +        (%w[. .. manifest.json index.md draft_index.md].include?(o)) || File.directory?("#{dir}/#{o}")
Если вместо `||` применить `or`, то скобки не потребуются

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    post = Post.new(manifest.symbolize_keys)
Лучше писать в функциональном стиле: `post = Post.new(manifest.symbolize_keys.merge(slug: ...))`

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    g = Git.open(Post.postsDir, :log => Logger.new(STDOUT))
`:log =>` запрещено писать :)

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    get_images_list.each_with_index.map do |img, id|
Давай лучше использовать «говорящий» стиль. Не «получить список изображений» и потом что-то с ним сделать, а «сделать со списком изображений то-то». Т.е. `images_list.each_with_index ...`

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    self.as_json
Лишний self

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    raise Exception.new('Args empty') if params.keys.empty?
Давай уточним тип исключения. Думаю, здесь лучше всего подходит ArgumentError.

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    slug = params.values[0]
Не очень хорошо так писать. Лучше так:

```
primary_key = params.keys.first

if params.length > 1 and primary_key != :slug
  ...
end

slug = params[:slug]
```

Плохо то, что магическое число 0 повторяется несколько раз. Тот факт, что мы пользуемся первым элементом, лучше локализовать во фрагменте как можно меньшего объема, чтобы, когда мы от этого откажемся, код изменился как можно меньше. Да и при чтении надо один раз увидеть, откуда мы что берём и дальше только концентрироваться на том, что мы уже достали, на том, что мы с этим объектом делаем.

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    PostsTag.where(slug: self.slug).map{|pt| pt.tag}
→ `.map(&:tag)` и self лишний

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +    # Rails use this method for nested CRUD
В этом же комментарии надо указать, почему этот метод пустой

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +        t = Tag.create!(text: tag['text'])
Не сокращай по возможности имена переменных. Только в конструкциях, где скорее всего никогда не допишут код и эта переменная не начнёт использоваться в большом количестве мест.

2020-07-28 01:12 UTC, levenkov commented on backend/app/models/post.rb
> +        if tag.include?('_destroy') && tag['_destroy'] == 'true'
Почему не просто `tag['_destroy'] == true`? Если ключа нет, будет nil (=false).

2020-07-29 09:53 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +        if tag.include?('_destroy') && tag['_destroy'] == 'true'
Поправила

2020-07-29 09:53 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +        t = Tag.create!(text: tag['text'])
Поправила

2020-07-29 09:54 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    # Rails use this method for nested CRUD
Написала

2020-07-29 09:55 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    PostsTag.where(slug: self.slug).map{|pt| pt.tag}
Поправлено в коммите с правками замечаний рубокопа

2020-07-29 09:55 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    slug = params.values[0]
Поправила

2020-07-29 09:56 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    raise Exception.new('Args empty') if params.keys.empty?
Здесь сделала ArgumentError, в остальных местах в рамках коммита с правками результатов рубокопа Exception заменен на StandardError

2020-07-29 09:57 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    self.as_json
Поправлено в коммите с правками замечаний рубокопа

2020-07-29 09:58 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    get_images_list.each_with_index.map do |img, id|
Поправлено в коммите с правками замечаний рубокопа

2020-07-29 09:58 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    g = Git.open(Post.postsDir, :log => Logger.new(STDOUT))
Поправлено в коммите с правками замечаний рубокопа

2020-07-29 09:58 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    post = Post.new(manifest.symbolize_keys)
Поправила

2020-07-29 09:59 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +        (%w[. .. manifest.json index.md draft_index.md].include?(o)) || File.directory?("#{dir}/#{o}")
Поправила

2020-07-29 09:59 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +  def self.postsDir
Поправлено в коммите с правками замечаний рубокопа

2020-07-29 09:59 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    @created_at = post[:created_at].nil? ? nil : post[:created_at].to_datetime
Поправила

2020-07-29 09:59 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    @published = post[:published] || false
Поправила здесь и в соседних строчках

2020-07-29 09:59 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +                :content,
Поправила

2020-09-10 12:02 UTC, levenkov commented
Давай подготовим PR к сдаче. Сейчас коммиты по PR отражают хронологию разработки. Надо переделать, чтобы они просто дробили большую работу на части, но никакой хронологии не прослеживалось.

> MELQ-30: Refactor post image routes
Этот коммит влей в тот коммит, в котором добавлены соответствующие строки.

2020-09-10 12:03 UTC, levenkov requested changes

2020-09-10 12:03 UTC, levenkov commented on backend/db/migrate/20181109115711_initial_migration.rb
> +      t.string :slug
Понятие slug применимо к большому количеству сущностей, не только к посту, поэтому `post_slug` (по аналогии с `post_id`)

2020-09-10 12:03 UTC, levenkov commented on backend/db/migrate/20181109115711_initial_migration.rb
> +      t.string :slug
`post_slug`

2020-09-10 12:03 UTC, levenkov commented on backend/db/migrate/20181109115711_initial_migration.rb
> +      t.string :slug
`post_slug`

2020-09-10 12:03 UTC, levenkov commented on gw/nginx.conf
> +      server frontend:3042;
Это какие-то правки, не относящиеся к сути коммита. Вынеси, пожалуйста в отдельный коммит.

2020-09-10 12:03 UTC, levenkov commented on backend/app/controllers/application_controller.rb
> +    puts "#{exception.class}: #{exception.message}"
В этом коммите и так очень много правок, трудно ревьюить.

Вынеси в другой коммит. Можно вместе с другими разнородными правками, не связанными с сутью тикета.

2020-09-10 12:03 UTC, levenkov commented on backend/app/models/tag.rb
> -  has_and_belongs_to_many :posts
А для чего нам сущность Tag?

2020-09-10 12:03 UTC, levenkov commented on backend/app/models/post.rb
> +    raise Exception.new('Args empty') if params.keys.empty?
Т.к. приходится смотреть тикет покоммитно, я прошу тебя перенести эту правку в исходный коммит. А то невозможно ревьюить.

2020-09-10 12:03 UTC, levenkov commented on backend/app/models/post.rb
> +    post = Post.new(manifest.symbolize_keys)
И эту правку тоже в исходный коммит перенеси, пожалуйста

2020-09-10 12:03 UTC, levenkov commented on backend/app/controllers/application_controller.rb
> -    puts "#{exception.class}: #{exception.message}"
Такое ощущение, что это было в одном коммите добавлено, в другом убрано. Убери этот мусор совсем.

2020-09-10 12:03 UTC, levenkov commented on backend/app/controllers/api/v1/posts_controller.rb
> +      def post
Не понял, почему мы убираем роут update? Обновлять пост каким роутом будем?

2020-09-10 12:10 UTC, levenkov commented
> MELQ-30: Add git
Давай чуть уточним, что в коммите делается. `MELQ-30: Introduce post pushing to git storage`

2020-09-10 12:28 UTC, levenkov commented
> MELQ-30: Add prepare script for creating/cloning git rep
Этот коммит давай сольём с предыдущим

2020-09-10 12:43 UTC, levenkov requested changes

2020-09-10 12:43 UTC, levenkov commented on backend/app/models/post.rb
> +    puts "FOOOO"
Clean

2020-09-10 12:43 UTC, levenkov commented on backend/posts/HEAD
> +ref: refs/heads/master
Репозиторий пушить в репозиторий не надо. Этот репозиторий должен создаваться. Кстати, хороший вопрос, в какой именно момент. Я думаю, логичным будет сделать создание по аналогии с созданием БД — через rake-таску.

2020-09-10 12:43 UTC, levenkov commented on prepare_remote_rep.sh
> +#!/bin/bash
А, мы вон как уже сделали. Тогда оставляй как есть + вот тикет на переделку в таску: https://github.com/bitia-ru/melq/issues/134

2020-09-10 12:43 UTC, levenkov commented on backend/app/models/post.rb
> -    puts "FOOOO"
Надо избавиться от этого мусорного коммита

2020-09-10 12:43 UTC, levenkov commented on convert_md_post_by_slug_to_html.js
> +let fs = require('fs');
Используй `const`, где можно.

2020-09-10 12:43 UTC, levenkov commented on convert_md_post_by_slug_to_html.js
> +fs.access(`${dirFrom}/${slug}/index.md`, fs.F_OK, (err) => {
Coding style: выделенные строки на каждый аргумент.

2020-09-10 12:43 UTC, levenkov commented on convert_md_post_by_slug_to_html.js
> +  console.log(marked(content));
Это точно нужно?

2020-09-10 12:43 UTC, levenkov commented on convert_md_posts_to_html.sh
> +for POST_DIR in $DIR_FROM/*; do
`$DIR_FROM/*` → `"$DIR_FROM"/*`

Поймёшь, почему так? :)

2020-09-10 12:43 UTC, levenkov commented on convert_md_posts_to_html.sh
> +DIR_FROM=$([ "$1" ] && echo "$1" || echo './storage/posts')
Переделка №1: `DIR_FROM=${1:-./storage/posts}`
Переделка №2: `DIR_FROM=${1:-./storage/posts}; shift` (и тогда во второй сторчке тоже `$1`)

2020-09-10 12:43 UTC, levenkov commented on convert_md_posts_to_html.sh
> +echo $1
Отладочный мусор?

2020-09-10 12:43 UTC, levenkov commented on convert_md_posts_to_html.sh
> +if [ ! -d "$DIR_FROM" ]; then
В bash-скриптах всегда используй двойные квадратные скобки

2020-09-10 12:43 UTC, levenkov commented on convert_md_posts_to_html.sh
> +    mkdir -p $DIR_TO/$SLUG
`"$DIR_TO/$SLUG"`

Все пути надо оборачивать в двойные кавычки

2020-09-10 12:43 UTC, levenkov commented on convert_md_posts_to_html.sh
> +      echo Post with slug $SLUG converted failed
Надо сохранять факт ошибки и при выходе из скрипта выставлять статус 0 если всё хорошо и 1 если были ошибки

2020-09-10 12:45 UTC, levenkov commented
> MELQ-30: Fix after review

Из этого коммита все правки, не являющиеся просто исправлением Coding Style, перенести в исходные тикеты, а что осталось слить с тикетом на исправление нарушений coding styles.

2020-09-10 12:45 UTC, levenkov requested changes

2020-09-10 12:45 UTC, levenkov commented on README.md
> +
Давай написание ридми вообще отдельным тикетом сделаем.

2020-09-10 12:48 UTC, levenkov commented
На скрипт генерации HTML на основе md лучше написать хотя бы простенький тест. Причем лучше выделить часть, которая получает на вход md-текст и на выход выдает HTML-текст и тестить именно эту функцию.

2020-09-11 10:08 UTC, SvetlanaBatova commented on backend/app/controllers/api/v1/posts_controller.rb
> +      def post
Роут мы не убираем, мы убираем метод, вместо него будет метод из purable, обновление будет происходить обычным образом

2020-09-11 10:10 UTC, levenkov commented on backend/app/controllers/api/v1/posts_controller.rb
> +      def post
Понял

2020-09-11 10:17 UTC, SvetlanaBatova commented on backend/app/models/tag.rb
> -  has_and_belongs_to_many :posts
Для хранения тегов. Мы обсуждали должно ли это быть отдельной сущностью или нет и пришли к выводу, что должно быть отдельной сущностью, насколько я помню из соображения, что 1) по нему будет поиск 2) видимо должна быть возможность получать список всех тегов, а это проще реализуется, когда тег отдельная сущность

2020-09-11 10:46 UTC, SvetlanaBatova commented on gw/nginx.conf
> +      server frontend:3042;
Это не нужно, это правка для запуска отдельно фронта

2020-09-11 11:10 UTC, SvetlanaBatova commented on convert_md_post_by_slug_to_html.js
> +  console.log(marked(content));
Вроде да. bash-скрипт перенаправляет stdout в файл, а console.log, если я правильно понимаю, пишет в stdout

2020-09-11 12:05 UTC, SvetlanaBatova commented on backend/app/controllers/application_controller.rb
> +    puts "#{exception.class}: #{exception.message}"
> На скрипт генерации HTML на основе md лучше написать хотя бы простенький тест. Причем лучше выделить часть, которая получает на вход md-текст и на выход выдает HTML-текст и тестить именно эту функцию.

Это делается функцией из подключаемой библиотеки, какой смысл ее тестировать?

2020-09-11 14:43 UTC, SvetlanaBatova commented on backend/db/migrate/20181109115711_initial_migration.rb
> +      t.string :slug
Переименовала

2020-09-11 14:43 UTC, SvetlanaBatova commented on backend/db/migrate/20181109115711_initial_migration.rb
> +      t.string :slug
Переименовала

2020-09-11 14:43 UTC, SvetlanaBatova commented on backend/db/migrate/20181109115711_initial_migration.rb
> +      t.string :slug
Переименовала

2020-09-11 14:44 UTC, SvetlanaBatova commented on backend/app/controllers/application_controller.rb
> -    puts "#{exception.class}: #{exception.message}"
Убрала

2020-09-11 14:44 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +    puts "FOOOO"
Убрала

2020-09-11 14:45 UTC, SvetlanaBatova commented on backend/posts/HEAD
> +ref: refs/heads/master
Для этого есть скрипт

2020-09-11 14:45 UTC, SvetlanaBatova commented on prepare_remote_rep.sh
> +#!/bin/bash
Ок

2020-09-11 14:45 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> -    puts "FOOOO"
Убрала

2020-09-11 14:45 UTC, SvetlanaBatova commented on convert_md_post_by_slug_to_html.js
> +let fs = require('fs');
Поправила

2020-09-11 14:45 UTC, SvetlanaBatova commented on convert_md_post_by_slug_to_html.js
> +fs.access(`${dirFrom}/${slug}/index.md`, fs.F_OK, (err) => {
Поправила

2020-09-11 14:46 UTC, SvetlanaBatova commented on convert_md_posts_to_html.sh
> +for POST_DIR in $DIR_FROM/*; do
Поправила

2020-09-11 14:46 UTC, SvetlanaBatova commented on convert_md_posts_to_html.sh
> +DIR_FROM=$([ "$1" ] && echo "$1" || echo './storage/posts')
Поправила

2020-09-11 14:46 UTC, SvetlanaBatova commented on convert_md_posts_to_html.sh
> +echo $1
Убрала

2020-09-11 14:46 UTC, SvetlanaBatova commented on convert_md_posts_to_html.sh
> +if [ ! -d "$DIR_FROM" ]; then
Поправила

2020-09-11 14:47 UTC, SvetlanaBatova commented on convert_md_posts_to_html.sh
> +    mkdir -p $DIR_TO/$SLUG
Поправила

2020-09-11 14:47 UTC, SvetlanaBatova commented on convert_md_posts_to_html.sh
> +      echo Post with slug $SLUG converted failed
Сделала

2020-09-11 15:27 UTC, SvetlanaBatova commented on README.md
> +
#137

2020-09-11 15:27 UTC, SvetlanaBatova commented
> > MELQ-30: Fix after review
> 
> Из этого коммита все правки, не являющиеся просто исправлением Coding Style, перенести в исходные тикеты, а что осталось слить с тикетом на исправление нарушений coding styles.

#135

2020-09-12 21:02 UTC, levenkov commented on convert_md_posts_to_html.sh
> +    if [[ $STATUS == 0 ]]; then
Арифметические выражения лучше через "арифметические скобки писать": `(( $STATUS == 0 ))`

2020-09-12 21:02 UTC, levenkov commented on convert_md_posts_to_html.sh
> +    if [[ $STATUS == 0 ]]; then
И в твоем решении, если где-то в середине будет ошибка, то STATUS перетрется.

2020-09-12 21:02 UTC, levenkov commented on backend/app/controllers/application_controller.rb
> +    puts "#{exception.class}: #{exception.message}"
А, раз там ничего специфического не делается, то ок, не надо тест.

2020-09-12 21:09 UTC, levenkov requested changes

2020-09-12 21:09 UTC, levenkov commented on backend/app/models/posts_tag.rb
> +class PostsTag < ApplicationRecord
Что здесь происходит? Мы добавили (зачем-то) новую модель, но нет миграции на неё. Ничего непонятно: зачем она нужна, как её использовать...

2020-09-12 21:16 UTC, levenkov requested changes

2020-09-12 21:16 UTC, levenkov commented on backend/app/models/post.rb
> +  attr_accessor(
Надо использовать ActiveModels. Вот пример для очень старых рельсов, просто чтобы проиллюстрировать идею: http://railscasts.com/episodes/219-active-model

Т.е. валидации можно будет почти не менять.

2020-09-12 21:18 UTC, levenkov commented
> MELQ-30: Fix auth

Это фикс деплоя. Его уж точно в отдельный **тикет** надо.

2020-09-12 21:22 UTC, levenkov requested changes

2020-09-12 21:22 UTC, levenkov commented on convert_md_post_by_slug_to_html.js
> +const fs = require('fs');
https://github.com/bitia-ru/melq/blob/master/frontend/ci/ci_entrypoint.sh#L7

Линтер не гоняется для этого файла. И нетривиально сделать, чтобы гонялся, поэтому пока просто вручную линтер для этого файла прогони.

2020-09-12 21:25 UTC, levenkov requested changes

2020-09-12 21:25 UTC, levenkov commented on backend/db/seeds.rb
> +  published: true
Комментарий к коммиту: Это не рефакторинг. Напомню, что рефакторинг — это изменение реализации без изменения интерфейса (правда надо всегда четко определять, на каком уровне рассматривается объект, т.к. любой программный кусок многослоен и интерфейсов на разных уровнях у него много).

2020-09-12 21:41 UTC, levenkov requested changes

2020-09-12 21:41 UTC, levenkov commented on backend/app/models/posts_tag.rb
> +class PostsTag < ApplicationRecord
В этот коммит надо вынести правки миграции по части тэгов + добавить строчкой выше определения класса комментарий `# Posts-to-tags many-to-many linking model`

Тогда лично мне будет понятно, что это за зверь.

2020-09-14 06:31 UTC, SvetlanaBatova commented
> > MELQ-30: Fix auth
> 
> Это фикс деплоя. Его уж точно в отдельный **тикет** надо.

#139

2020-09-14 09:25 UTC, SvetlanaBatova commented on convert_md_posts_to_html.sh
> +    if [[ $STATUS == 0 ]]; then
Поправила

2020-09-14 09:25 UTC, SvetlanaBatova commented on backend/app/models/posts_tag.rb
> +class PostsTag < ApplicationRecord
Поправила

2020-09-14 09:26 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +  attr_accessor(
Возникает проблема с тем, что для Post требуются дополнительные методы, которые сейчас не реализованы

2020-09-14 09:27 UTC, SvetlanaBatova commented on convert_md_post_by_slug_to_html.js
> +const fs = require('fs');
Прогнала, поправила

2020-09-14 09:27 UTC, SvetlanaBatova commented on backend/db/seeds.rb
> +  published: true
Переименовала

2020-09-22 09:54 UTC, levenkov requested changes

2020-09-22 09:54 UTC, levenkov commented on .gitignore
> +/node_modules
Не надо в корень коммитить node_modules. Я пока не знаю, как с этим поступать, просто не коммитим.

2020-09-22 09:54 UTC, levenkov commented on convert_md_post_by_slug_to_html.js
> +    console.log(marked(content));
console.log не должен использоваться для целей вывода в STDOUT содержимого файла. Для этой цели надо использовать `process.stdout.write`

2020-09-22 09:54 UTC, levenkov commented on prepare_remote_rep.sh
> +if [ -n "$REMOTE_REPO" ]
1. Тут не поправила скобки.
2. Этот файл похоже не правильно работает в случае удаленного репозитория. Протестируй этот сценарий, пожалуйста.

2020-10-10 06:18 UTC, levenkov approved these changes

2020-10-10 06:22 UTC, merged