WIP: MELQ-35: Сделать роут /components/example с шаблоном для компонента
bitia-ru/melq pull request #36
Opened 2020-06-16 16:23 UTC by SvetlanaBatova

2020-06-17 08:20 UTC, levenkov requested changes
Проверь coding styles. Как минимум V1.jsx явные нарушения есть, на которые даже IDE ругаться должна.

2020-06-17 08:20 UTC, levenkov commented on frontend/src/v1/examples/index.js
> +const examples = () => (
Какой смысл делать тут функцию? Почему просто словарем не задать?

2020-06-17 08:51 UTC, SvetlanaBatova commented on frontend/src/v1/examples/index.js
> +const examples = () => (
никакого, поменяла на словарь

2020-06-17 09:15 UTC, levenkov approved these changes

2020-07-02 18:08 UTC, levenkov approved these changes

2020-07-02 18:08 UTC, merged