MELQ-37: Сделать компонент Button
bitia-ru/melq pull request #38
Opened 2020-06-18 19:50 UTC by SvetlanaBatova

2020-07-20 11:12 UTC, SergBlack approved these changes

2020-07-27 23:36 UTC, levenkov requested changes

2020-07-27 23:36 UTC, levenkov commented on frontend/src/v1/components/Button/ButtonLayout.jsx
> +  if (!btnStyle) {
Почему не сделать как-то так?
`themeStyle[btnStyle + 'Color'] || themeStyle.defaultColor`

2020-07-27 23:36 UTC, levenkov commented on frontend/src/v1/components/Button/ButtonLayout.jsx
> +  if (btnStyle === 'transparent') {
Вроде это прямо тот самый случай, для которого был придуман `switch`

2020-07-27 23:36 UTC, levenkov commented on frontend/src/v1/components/Button/ButtonLayout.jsx
> +            size === 'small' ? styles.btnSmall : '',
А вот так тут нельзя написать? `size === 'small' && styles.btnSmall`

2020-07-27 23:36 UTC, levenkov commented on frontend/src/v1/components/Button/ButtonLayout.jsx
> +    false,
Что значат эти параметры? В таких случаях лучше использовать именованные аргументы (в JS их нативно нет, но можно использовать словарь)

2020-07-28 07:45 UTC, SvetlanaBatova commented on frontend/src/v1/components/Button/ButtonLayout.jsx
> +  if (!btnStyle) {
Сделала

2020-07-28 07:45 UTC, SvetlanaBatova commented on frontend/src/v1/components/Button/ButtonLayout.jsx
> +  if (btnStyle === 'transparent') {
Поменяла на switch

2020-07-28 07:46 UTC, SvetlanaBatova commented on frontend/src/v1/components/Button/ButtonLayout.jsx
> +            size === 'small' ? styles.btnSmall : '',
Можно, поправила здесь и в соседних строчках

2020-07-28 07:46 UTC, SvetlanaBatova commented on frontend/src/v1/components/Button/ButtonLayout.jsx
> +    false,
Переделала на словарь

2020-07-28 08:37 UTC, levenkov requested changes

2020-07-28 08:37 UTC, levenkov commented on frontend/src/v1/examples/ButtonExample.js
> +  useEffect(() => {
Многострочный вызов функции: каждый аргумент должен быть на выделенных строках.

2020-07-28 08:37 UTC, levenkov commented on frontend/src/v1/screens/PostShow.jsx.orig
> +      <MainScreen
Зачем здесь переносы строк? Всего один аттрибут же

2020-07-28 08:37 UTC, levenkov commented on frontend/src/v1/screens/PostShow.jsx.orig
> +                <Link to="/">Back</Link>|
Символ `|` лучше на отдельную строку расположить, а то его плохо «видно»

2020-07-28 11:13 UTC, SvetlanaBatova commented on frontend/src/v1/examples/ButtonExample.js
> +  useEffect(() => {
Тут не нужен многострочный вызов, все влезает в одну строку, поправила

2020-07-28 11:15 UTC, SvetlanaBatova commented on frontend/src/v1/screens/PostShow.jsx.orig
> +      <MainScreen
Это файл orig, который по ошибке затесался в коммит, а том файле, который используется здесь нет переноса строки. Файл orig удалила

2020-07-28 11:15 UTC, SvetlanaBatova commented on frontend/src/v1/screens/PostShow.jsx.orig
> +                <Link to="/">Back</Link>|
Это файл orig, который по ошибке затесался в коммит, а том файле, который используется здесь | на отдельной строке. Файл orig удалила

2020-07-28 11:24 UTC, levenkov approved these changes

2020-07-28 11:35 UTC, merged