WIP: MELQ-3: Posts CRUD
bitia-ru/melq pull request #4
Opened 2020-05-26 20:08 UTC by SvetlanaBatova

2020-05-28 18:04 UTC, levenkov requested changes

2020-05-28 18:04 UTC, levenkov commented on backend/db/migrate/20181109115711_initial_migration.rb
> +      t.column :can_comment, :can_comment, default: 'auth_only'
Надо подправить в соответствии с правкой в MELQ-1

2020-05-29 07:39 UTC, levenkov requested changes

2020-05-29 07:39 UTC, levenkov commented on backend/app/controllers/api/v1/posts_controller.rb
> +        instance_variable_set("@#{resource_name}", Post.find_by(slug: params[:slug]))
Здесь можно написать просто `@post = Post.find_by(...)`.

Мы так иногда не пишем, но только в том коде, который хотим сделать переносимым. Эта строчка по определению не переносима, т.к. ты явно указываешь имя модели - `Post`. Т.е. либо надо ее сделать переносимой, либо сделать ее проще. Я за второе, в данном случае переносимость нам вряд ли пригодится.

2020-05-29 07:39 UTC, levenkov commented on backend/app/models/post.rb
> +  accepts_nested_attributes_for :attachments_attachments, allow_destroy: true
Почему такое имя? Почему не сделать attachments?

2020-05-29 07:39 UTC, levenkov commented on backend/config/routes.rb
> +      get '/posts/:slug', to: 'posts#show'
Если нам не нужно обращения к посту по id (а вроде не нужно), то можно сделать просто так: `resources :posts, param: :slug`

2020-05-29 07:39 UTC, levenkov commented on frontend/src/v1/screens/PostEdit.jsx
> +          slug && <Button
Так писать нельзя. Если не влезает в строчку, то

```
slug && (
  ...
)
```

2020-05-29 07:39 UTC, levenkov commented on frontend/src/v1/screens/PostEdit.jsx
> +        <Button
Точно ведь в строчку влезает, зачем здесь переносы?

2020-06-01 08:01 UTC, SvetlanaBatova commented on backend/db/migrate/20181109115711_initial_migration.rb
> +      t.column :can_comment, :can_comment, default: 'auth_only'
Поправила

2020-06-01 08:01 UTC, SvetlanaBatova commented on backend/app/controllers/api/v1/posts_controller.rb
> +        instance_variable_set("@#{resource_name}", Post.find_by(slug: params[:slug]))
Поменяла на @post = Post.find_by(...)

2020-06-01 08:05 UTC, SvetlanaBatova commented on backend/app/models/post.rb
> +  accepts_nested_attributes_for :attachments_attachments, allow_destroy: true
Это имя формируется рельсами как имя того, для чего прописано has_many_attached + _attachments, то для чего прописано has_many_attached тоже называлось attachments, поэтому получилось такое странное имя. Переименовала так, чтобы было has_many_attached :images, тогда здесь получается images_attachments. И везде, во фронте тоже переименовала attachments в images, чтобы не было путаницы

2020-06-01 08:06 UTC, SvetlanaBatova commented on backend/config/routes.rb
> +      get '/posts/:slug', to: 'posts#show'
Поправила

2020-06-01 08:06 UTC, SvetlanaBatova commented on frontend/src/v1/screens/PostEdit.jsx
> +          slug && <Button
Поправила

2020-06-01 08:06 UTC, SvetlanaBatova commented on frontend/src/v1/screens/PostEdit.jsx
> +        <Button
Сделала в одну строчку

2020-06-06 21:32 UTC, levenkov approved these changes

2020-06-06 21:33 UTC, merged