MELQ-41: Add component CheckBox
bitia-ru/melq pull request #42
Opened 2020-06-19 12:38 UTC by SergBlack

2020-06-19 12:49 UTC, levenkov commented
Я не запускал, но, судя по коду, внешний вид этого чек-бокса совсем не такой, как в нашем дизайне. Надо делать уже, чтобы компонент выглядел ровно как в дизайне.

Вообще, насколько я знаю, чек-бокс невозможно изменить внешне, если делать его через тег `input`. Надо делать вручную его через div’ы.

2020-06-19 12:51 UTC, levenkov requested changes
Отписался выше.

2020-06-19 16:19 UTC, SergBlack commented
Зарефакторил, постарался все учесть

2020-06-20 12:19 UTC, SergBlack commented
С последним коммитом внесены следующие изменениях: 1) перенес svg, 2) прописал логику для disabled, 3) добавил в пропсы value, onChange, name, 4) добавил tooltip, 5) сделал exampleCheckbox страницу, роут компонента localhost/components/check_box

2020-07-03 22:13 UTC, levenkov commented
Посмотри, как выглядит курсор, когда ты наводишь мышь на нативный чекбокс. Там курсор-рука. Нам надо такой же сделать.

2020-07-09 09:48 UTC, SergBlack commented
Добавил tooltip, стили для outline и курсор pointer

2020-07-11 17:28 UTC, SvetlanaBatova commented on frontend/src/v1/components/CheckBox/assets/check.svg
> +</svg>
нужен перенос строки

2020-07-11 17:31 UTC, SvetlanaBatova reviewed
Лучше переименовать CheckBox.js в CheckBox.jsx для единообразия

2020-07-14 09:48 UTC, SvetlanaBatova commented on frontend/src/v1/components/CheckBox/CheckBox.js
> +    outlineColor: infoColor,
Лучше ребейзнуть на MELQ-78 и брать этот стиль из theme

2020-07-14 09:48 UTC, SvetlanaBatova commented on frontend/src/v1/components/CheckBox/CheckBox.js
> +  onClick: PropTypes.func.isRequired,
Если можно здесь обойтись без isRequired, то лучше считать, что если disabled не задано, то оно false, если checked не задано, то оно false, если onClick не задано, то по клику ничего не происходит

2020-07-14 09:48 UTC, SvetlanaBatova commented on frontend/src/v1/examples/CheckBoxExample.js
> +          tooltipSide="right"
Если не задать параметры тултипа, то отображение будет некорректным, потому что будет отображаться пустой тултип

2020-07-14 10:29 UTC, SvetlanaBatova commented
Почему-то на странице с примером компонента присутствует вертикальная прокрутка

2020-07-16 09:10 UTC, SergBlack commented on frontend/src/v1/components/CheckBox/assets/check.svg
> +</svg>
Добавлен

2020-07-16 09:10 UTC, SergBlack commented
> Лучше переименовать CheckBox.js в CheckBox.jsx для единообразия

Переименован

2020-07-16 09:11 UTC, SergBlack commented on frontend/src/v1/components/CheckBox/CheckBox.js
> +  onClick: PropTypes.func.isRequired,
Поправлено

2020-07-16 09:12 UTC, SergBlack commented on frontend/src/v1/examples/CheckBoxExample.js
> +          tooltipSide="right"
Добавлена утилита ConditionalWrapper

2020-07-16 09:12 UTC, SergBlack commented
> Почему-то на странице с примером компонента присутствует вертикальная прокрутка

Поправил margin

2020-07-16 09:39 UTC, SergBlack commented on frontend/src/v1/components/CheckBox/CheckBox.js
> +    outlineColor: infoColor,
Поправил

2020-07-16 11:25 UTC, SvetlanaBatova approved these changes

2020-07-16 11:31 UTC, SvetlanaBatova reviewed
Небольшие замечания остались, со остальным вроде все ок

2020-07-16 11:31 UTC, SvetlanaBatova commented on frontend/src/v1/components/CheckBox/CheckBox.jsx
> +  id: PropTypes.string.isRequired,
А id зачем required? Может же быть просто <input type="checkbox" /> без id, зачем здесь id обязательно требовать?

2020-07-16 11:31 UTC, SvetlanaBatova commented on frontend/src/v1/components/CheckBox/CheckBoxLayout.jsx
> +  successColor, themeStyles,
Лучше перенос строки перед themeStyles добавить

2020-07-16 11:49 UTC, SvetlanaBatova commented
В дизайне кроме варианта размера 24*24, есть еще 16*16, надо, чтобы компонент поддерживал оба варианта

2020-07-16 12:22 UTC, SvetlanaBatova commented on frontend/src/v1/components/CheckBox/CheckBoxLayout.jsx
> +    outlineColor: infoColor,
Зачем здесь оставлен цвет, если берется стиль из theme?

2020-07-16 13:56 UTC, SergBlack commented on frontend/src/v1/components/CheckBox/CheckBox.jsx
> +  id: PropTypes.string.isRequired,
Погуглил и получается, что id для inputa нужен в том случае, если его надо связать с <label> поэтому действительно тут это излишне. Убрал

2020-07-16 13:57 UTC, SergBlack commented on frontend/src/v1/components/CheckBox/CheckBoxLayout.jsx
> +  successColor, themeStyles,
Поправил

2020-07-16 14:07 UTC, SergBlack commented on frontend/src/v1/components/CheckBox/CheckBoxLayout.jsx
> +    outlineColor: infoColor,
Проглядел. Удалил

2020-07-16 14:07 UTC, SergBlack commented
> В дизайне кроме варианта размера 24х24, есть еще 16х16, надо, чтобы компонент поддерживал оба варианта
Добавлено

2020-07-16 19:41 UTC, SvetlanaBatova approved these changes

2020-07-16 19:55 UTC, SvetlanaBatova approved these changes

2020-07-28 13:44 UTC, levenkov requested changes

2020-07-28 13:44 UTC, levenkov commented on frontend/src/v1/components/CheckBox/CheckBox.jsx
> +  useEffect(() => {
Если вызов функции занимает больше одной строки, аргументы должны быть на выделенных под них строках.

```
useEffect(
  a,
  b,
)
```

2020-07-28 13:45 UTC, SvetlanaBatova approved these changes

2020-07-28 13:57 UTC, SergBlack commented on frontend/src/v1/components/CheckBox/CheckBox.jsx
> +  useEffect(() => {
Поправлено

2020-07-28 14:08 UTC, merged