MELQ-67: Сделать компонент PhotoPreview
bitia-ru/melq pull request #69
Opened 2020-07-03 17:16 UTC by SvetlanaBatova

2020-07-03 22:27 UTC, levenkov commented
На возможность нажатия должен указывать указатель «рука».

2020-07-08 12:10 UTC, SvetlanaBatova commented
> На возможность нажатия должен указывать указатель «рука».

Поправила

2020-07-19 08:33 UTC, SergBlack requested changes
В дизайне под изображением есть текстовое описание названия загружаемого файла. В компоненте не увидел

2020-07-20 09:39 UTC, SvetlanaBatova commented
> В дизайне под изображением есть текстовое описание названия загружаемого файла. В компоненте не увидел

Добавила подпись с возможностью ее редактирования (для перехода в режим редактирования используется двойной клик левой кнопкой мыши или tab+Enter, для выхода из режима редактирования надо либо кликнуть в сторону, либо нажать на Enter)

2020-07-20 10:13 UTC, SergBlack approved these changes

2020-07-27 23:34 UTC, levenkov approved these changes

2020-07-27 23:35 UTC, merged