WIP: MELQ-63: Сделать компонент Card
bitia-ru/melq pull request #79
Opened 2020-07-11 16:06 UTC by SergBlack

2020-07-11 17:35 UTC, SvetlanaBatova commented on frontend/src/v1/components/Card/Card.jsx
> +  width: PropTypes.string.isRequired,
Мне isRequired лучше не делать, может быть например вариант, когда нужно растянуть карточку до размера контента

2020-07-11 17:36 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +    defaultFont={themeStyles.defaultFont}
Лучше чтобы Card брал шрифты из theme, как другие компоненты

2020-07-11 17:38 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +    </div>
Если сделать отдельные компоненты для разных счетчиков на базе Counter, то тут код будет более читаемым и перечень пропсов будет короче

2020-07-11 17:42 UTC, SvetlanaBatova commented on frontend/src/v1/examples/PostCardExample.js
> +          imageSrc={require('./images/postCard_demo_image.png')}
Посмотри какие поля есть в post сейчас, надо сделать так, чтобы PostCard мог получить на вход объект post, а дальше доставал нужные поля, картинки итд уже внутри себя

2020-07-12 08:08 UTC, SergBlack commented on frontend/src/v1/components/Card/Card.jsx
> +  width: PropTypes.string.isRequired,
Согласен, убрал.

2020-07-12 08:10 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +    defaultFont={themeStyles.defaultFont}
Поправил

2020-07-12 21:40 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +    </div>
Сделан рефакторинг

2020-07-12 21:41 UTC, SergBlack commented on frontend/src/v1/examples/PostCardExample.js
> +          imageSrc={require('./images/postCard_demo_image.png')}
Постарался сделать что-то похожее на то, что сейчас есть в post

2020-07-14 10:32 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +  posts: PropTypes.array.isRequired,
PostCard это одна карточка, в нее не должно передаваться posts, надо передавать данные только одного поста, map будет вне этого компонента

2020-07-14 11:04 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +  posts: PropTypes.array.isRequired,
Вынес вне компонента

2020-07-14 11:44 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +                    src={post.images[0].url}
Вроде решили, что здесь будет отображаться не первая картинка из images, а отдельная картинка, которая будет грузиться для карточки

2020-07-14 11:44 UTC, SvetlanaBatova commented on frontend/src/v1/components/Card/Card.jsx
> +        boxShadow: '0px 10px 20px rgba(32, 32, 40, 0.05)',
Под это есть стиль в theme

2020-07-14 11:44 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +              />
Если ставить фото другого формата, то съезжает верстка

2020-07-14 11:44 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +const getDate = date => new Date(date).toLocaleDateString('ru-RU');
Предлагаю для форматирования даты использовать https://github.com/iamkun/dayjs эта библиотека уже подключена к проекту

2020-07-14 11:44 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +                className={css(styles.image)}
Стиль image в styles не прописан

2020-07-14 11:44 UTC, SvetlanaBatova commented on frontend/src/v1/index.js
> +import './fonts.css';
это вынесено в отдельный тикет

2020-07-14 11:50 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +      <span className={css(styles.header)}>{post.topic}</span>
Для даты и темы цвета по виду отличаются от того, что в дизайне

2020-07-14 17:28 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +                    src={post.images[0].url}
Да, все верно, это уже поправлено на момент комментария.

2020-07-14 17:28 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +              />
Поправил стили.

2020-07-14 18:42 UTC, SergBlack commented on frontend/src/v1/components/Card/Card.jsx
> +        boxShadow: '0px 10px 20px rgba(32, 32, 40, 0.05)',
Заменен

2020-07-14 18:43 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +                className={css(styles.image)}
Исправлено

2020-07-14 18:44 UTC, SergBlack commented on frontend/src/v1/index.js
> +import './fonts.css';
Убрано

2020-07-14 19:01 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +      <span className={css(styles.header)}>{post.topic}</span>
Исправлено

2020-07-14 19:15 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +const getDate = date => new Date(date).toLocaleDateString('ru-RU');
Заменил

2020-07-14 19:21 UTC, SergBlack commented on frontend/src/v1/index.js
> +import './fonts.css';
Сделал ребейз на 78 и изменил base

2020-07-16 13:43 UTC, SvetlanaBatova requested changes

2020-07-16 13:43 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +              />
Беру урл изображения, например отсюда https://picsum.photos/, запускаю то, что сейчас есть и в браузере подменяю урл изображения на свое, ожидаю, что изображение как-то урежется под нужный размер, но при этом верстка не уедет, т.е. изображение не будет наползать на текст, но оно наползает. В данном случае возможно лучше использовать не img тег, а делать так, чтобы изображение подставлялось как background-image c background-size: cover

2020-07-16 13:43 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +        onClick={onClick}
А почему здесь у всех каунтеров один onClick, надо же как-то определять на что нажали, т.е. можно наверное из event это доставать, но не уверена, что это удобно, проще в onClick передавать какой-нибудь айдюк, чтобы было понятно на что нажали

2020-07-16 13:43 UTC, SvetlanaBatova commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +  onClick: PropTypes.func.isRequired,
В карточку надо как-то еще передавать инфу о том, как ей отображать каунтеры. Допустим может быть юзер, которому разрешен только просмотр и оставлять комментарии он не может, т.е. ему карточка должна отображаться так, что кнопка перейти к комментарию на нажатие реагировать не должна. Аналонично для остальных каунтеров.

2020-07-16 20:42 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +              />
Для родительского элемента <img> добавлено overflow: 'hidden',

2020-07-16 20:56 UTC, SergBlack commented on frontend/src/v1/components/PostCard/PostCard.jsx
> +        onClick={onClick}
Добавил в функцию. В консоли можно посмотреть на что был клик.

2020-07-17 17:51 UTC, SvetlanaBatova approved these changes

2020-07-18 00:20 UTC, levenkov approved these changes

2020-07-18 00:20 UTC, merged