MELQ-81: Сделать компонент Error
bitia-ru/melq pull request #82
Opened 2020-07-11 17:55 UTC by SvetlanaBatova

2020-07-19 08:21 UTC, SergBlack commented
Дизайн изменился)

2020-07-28 11:43 UTC, levenkov requested changes
В примере нужно дать возможность задать текст плашки, чтобы, например, проверить, что будет, если задать слишком большой текст или многострочный текст.

2020-07-28 13:04 UTC, SvetlanaBatova commented
> В примере нужно дать возможность задать текст плашки, чтобы, например, проверить, что будет, если задать слишком большой текст или многострочный текст.

Добавила возможность в примере ввести текст плашки. Переделала отображение ошибки на новый вариант, тот, который без красного фона

2020-07-28 13:20 UTC, levenkov approved these changes

2020-07-28 13:21 UTC, merged