MELQ-83: Сделать компонент Item
bitia-ru/melq pull request #84
Opened 2020-07-11 18:06 UTC by SvetlanaBatova

2020-07-19 08:15 UTC, SergBlack approved these changes

2020-07-24 21:31 UTC, levenkov requested changes

2020-07-24 21:31 UTC, levenkov commented on frontend/src/v1/components/Item/Item.jsx
> +      onClick && onClick();
Клик — это клик _мыши_.

Тут тогда надо использовать термин `triggered`.

2020-07-24 22:04 UTC, SvetlanaBatova commented on frontend/src/v1/components/Item/Item.jsx
> +      onClick && onClick();
Поправила

2020-07-27 22:36 UTC, levenkov approved these changes

2020-07-27 22:38 UTC, merged