MELQ-88: Сделать компонент Input
bitia-ru/melq pull request #89
Opened 2020-07-13 14:03 UTC by SvetlanaBatova

2020-07-17 13:09 UTC, SergBlack requested changes
По дизайну присутствует состояние disabled, но в компоненте не увидел.

2020-07-17 17:41 UTC, SvetlanaBatova commented
> По дизайну присутствует состояние disabled, но в компоненте не увидел.

Добавила disabled

2020-07-17 17:57 UTC, SergBlack approved these changes

2020-07-27 23:13 UTC, levenkov approved these changes

2020-07-27 23:13 UTC, merged