MELQ-90: Сделать компонент TextArea
bitia-ru/melq pull request #91
Opened 2020-07-13 15:32 UTC by SvetlanaBatova

2020-07-17 12:43 UTC, SergBlack requested changes
По дизайну присутствует состояние disabled, но в компоненте не увидел. Так же в стилях для textarea, по моему мнению, надо добавить запрет на изменение размера resize: none, либо прописать это как-то через пропсы, если нужно будет где-то разрешать изменять размер.

2020-07-17 17:40 UTC, SvetlanaBatova commented
> По дизайну присутствует состояние disabled, но в компоненте не увидел. Так же в стилях для textarea, по моему мнению, надо добавить запрет на изменение размера resize: none, либо прописать это как-то через пропсы, если нужно будет где-то разрешать изменять размер.

Disabled добавила. Resize: 'none' нужен, согласна, добавила

2020-07-17 17:57 UTC, SergBlack approved these changes

2020-07-18 00:53 UTC, levenkov approved these changes

2020-07-18 00:54 UTC, merged